### ISSUE TITLE
Code enhancement

### ISSUE THREAD

**Issue by tmachyshyn** [dubas-pro/ext-dubas-google-fonts#4]
Hello,

Thanks for this extensions.

Some code can be improved. For running the script while the Rebuild, please use the code like here: https://github.com/espocrm/espocrm/blob/0582fd680dda11dd896c09a949c8b464caeab57c/application/Espo/Resources/metadata/app/rebuild.json.
This is available from EspoCRM v.7.1+

**Comment by emillod** [comment]
Hello @tmachyshyn 
i've implemented rebuild action. Here you have [changed files](https://github.com/dubas-pro/ext-dubas-google-fonts/commit/5a1e099b8aa8fc3e65d393c8c0e027519ec791ff).

Let me know if you need anything.

**Comment by tmachyshyn** [comment]
Thanks
